---
title: "Chapter 4"
author: "Michael McCann"
date: "7/18/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)

```

# Chapter 4

## Exercise 4.4.1:

Why does this code not work?

my_variable <- 10
my_varıable

Look carefully! (This may seem like an exercise in pointlessness, but training your brain to notice even the tiniest difference will pay off when programming.)

```{r}
# The i in the second my_variable isn't an i...                                   

```

##Exercise 4.4.2:

Tweak each of the following R commands so that they run correctly:

ggplot(dota = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy))
  
fliter(mpg, cyl = 8)
filter(diamond, carat > 3)

```{r}
#change dota to data

ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy))

#change fliter to filter 
#change = into a ==
filter(mpg, cyl == 8)

#change diamond to diamonds
filter(diamonds, carat > 3)

```


Press Alt + Shift + K. What happens? How can you get to the same place using the menus?
```{r}

#Alt+shift+K pulls up the keyboard shortcut list. This can also be found under the help menu 
```


