---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

```{r}
KoreanConflict <- read_csv("KoreanConflict.csv")

# rm(Koreanconflict)

glimpse(KoreanConflict)
head(KoreanConflict)
```

```{r}
KoreanConflict %>% 
  select(BRANCH, FATALITY) %>% 
  filter(FATALITY == "KILLED IN ACTION") %>% 
  group_by(BRANCH, FATALITY) %>% 
  summarize(total_kia = n()) %>% 
  arrange(-(total_kia)) %>% 
  ungroup() %>% 
  ggplot(aes(x = reorder(BRANCH, total_kia), y = total_kia)) +
  geom_col() +
  coord_flip()
  

```

```{r}
ggplot(data = mpg) +
  geom_point(mapping = aes(x = displ, y = hwy, color = class))


ggplot(data = mpg) +
  geom_point(mapping = aes(x = cyl, y = hwy))

```

```{r}
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, color = displ < 5))


dim(mpg)
```


```{r}
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy)) + 
  facet_grid(. ~ cyl)


ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy)) + 
  facet_wrap(~ cty)

ggplot(data = mpg) + 
  geom_point(mapping = aes(x = drv, y = cyl))

ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy)) +
  facet_grid(drv ~ .)

ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy)) +
  facet_grid(. ~ cyl)
```

